<?php

namespace app\base;

use yii\web\Controller;
use yii\web\HttpException;

class BaseController extends Controller
{
    public function afterAction($action, $result)
    {
        $result = parent::afterAction($action, $result);

        $url = \Yii::$app->request->url;
       // \Yii::$app->session->set('last_page_url',$url);
        \Yii::$app->session->setFlash('success',$url); // success
        return $result;
    }

    public function beforeAction($action)
    {
        if (\Yii::$app->user->isGuest){
            throw new HttpException(401,'Need authorisation');
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

}